version: '3.8'

services:
  vehicle:
    image: mongo:latest
    container_name: vehicle
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  inspector:
    image: postgres:latest
    container_name: inspector
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=inspectordb
    ports:
      - "5433:5432"

  inspector-app:
    image: anagenova/inspector
    container_name: inspector-app
    ports:
      - "8081:8081"

  vehicle-app:
    image: julioborges05/vehicle
    container_name: vehicle-app
    ports:
      - "8080:8080"

volumes:
  mongo-data: